In [1]:
import torch

In [7]:
tensor1 = torch.tensor([[1.,2.,3.],
                       [4.,5.,6.]])

In [11]:
tensor2 = torch.tensor([[7.,8.,9.],
                       [10.,11.,12.]])


In [12]:
print(tensor1.requires_grad)
print(tensor2.requires_grad)

True
False


In [13]:
# we need to set it to True

tensor1.requires_grad_()
tensor2.requires_grad_()

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]], requires_grad=True)

In [14]:
print(tensor1.grad) # nothinh till now

None


In [15]:
print(tensor1.grad_fn)

None


In [16]:
# lets create  a computation 
output_tensor = tensor1 * tensor2


In [17]:
output_tensor.requires_grad

True

In [18]:
output_tensor =(tensor1 * tensor2).mean()

In [19]:
output_tensor

tensor(36.1667, grad_fn=<MeanBackward0>)

In [20]:
output_tensor.backward()

In [21]:
tensor1.grad

tensor([[1.1667, 1.3333, 1.5000],
        [1.6667, 1.8333, 2.0000]])

In [22]:
tensor1.grad.shape, tensor1.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [23]:
# lets use some python fucntions

In [24]:
def calculate(t):
    return t*2


In [25]:
@torch.no_grad()
def calculate_with_no_grad(t):
    return t*2

In [27]:
result_tensor = calculate(tensor1)
result_tensor

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], grad_fn=<MulBackward0>)

In [28]:
result_tensor.requires_grad

True

In [29]:
result_tensor_no_grad = calculate_with_no_grad(tensor1)
result_tensor_no_grad

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [30]:
with torch.no_grad():
    new_tensor_no_grad = tensor1 *3
    print('new_tensor_no_grad = ', new_tensor_no_grad)
    
    with torch.enable_grad():
        new_tensor_grad = tensor1 *3
        print('new_tensor_grad', new_tensor_grad)

new_tensor_no_grad =  tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]])
new_tensor_grad tensor([[ 3.,  6.,  9.],
        [12., 15., 18.]], grad_fn=<MulBackward0>)


In [33]:
# also we can use like this

tensor_one = torch.tensor([[1.0, 2.0],
                          [3.0, 4.0]], requires_grad= True)

tensor_one

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [39]:
tensor_two = torch.tensor([[5.,6.],
                          [7.,8.]])

tensor_two

tensor([[5., 6.],
        [7., 8.]])

In [40]:
print(tensor_one.requires_grad)

True


In [41]:
print(tensor_two.requires_grad)

False


In [42]:
# making it true so that gadietns can be computed and updated as btracking is enabled

In [43]:
tensor_two.requires_grad_()

tensor([[5., 6.],
        [7., 8.]], requires_grad=True)

In [44]:
print(tensor_two.requires_grad)

True


In [45]:
final_tensor = (tensor_one + tensor_two).mean()

In [46]:
final_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [48]:
print(tensor_one.grad)
print(tensor_two.grad) 
# None because onyl forward pass is done till now

None
None


In [49]:
final_tensor.backward()

In [51]:
print(tensor_one.grad)
print(tensor_two.grad)

tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])


In [52]:
# we can use detached tensor if we want nto to update in one copy of tensor
# lets loook at through the example

In [53]:
detached_tensor = tensor_one.detach()
detached_tensor

tensor([[1., 2.],
        [3., 4.]])

In [54]:
mean_tensor= (tensor_one +tensor_two).mean()

In [55]:
mean_tensor

tensor(9., grad_fn=<MeanBackward0>)

In [56]:
mean_tensor.backward()

In [57]:
tensor_one.grad

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])

In [59]:
detached_tensor.grad # no grads as it was detached tensor