In [1]:
import torch

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Initialise tensors

In [4]:
x =torch.ones(3,2)
print(x)
x = torch.zeros(3,2)
print(x)
x = torch.rand(3,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.4860, 0.4222],
        [0.6915, 0.7974],
        [0.5716, 0.8260]])


In [5]:
x = torch.empty(3,2)
print(x)

tensor([[-5.0457e+07,  4.5583e-41],
        [-5.0457e+07,  4.5583e-41],
        [ 4.4842e-44,  0.0000e+00]])


In [7]:
y =torch.zeros_like(x)
print(y)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
x =torch.linspace(0,1,5)

In [9]:
x

tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

In [17]:
x = torch.tensor([[1,2],[2,3], [5,6]])

In [18]:
x

tensor([[1, 2],
        [2, 3],
        [5, 6]])

In [19]:
#slicing

In [20]:
print(x.size())

torch.Size([3, 2])


In [21]:
print(x[:,1])

tensor([2, 3, 6])


In [22]:
print(x[0, :])

tensor([1, 2])


In [24]:
#reshapinh

In [25]:
print(x)

tensor([[1, 2],
        [2, 3],
        [5, 6]])


In [26]:
y = x.view(2,3)

In [27]:
y

tensor([[1, 2, 2],
        [3, 5, 6]])

In [28]:
y = x.view(6,-1)

In [29]:
y

tensor([[1],
        [2],
        [2],
        [3],
        [5],
        [6]])

In [30]:
#simple tneosr oprations

In [31]:
x= torch.ones([3,2])
y = torch.ones([3,2])
z =x +y
print(z)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [32]:
z = y.add(x)

In [33]:
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [34]:
z= y.add_(x)

In [35]:
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [36]:
y

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [37]:
#Numpy vd tensots


In [38]:
x_np = x.numpy()
print(type(x), type(x_np))

<class 'torch.Tensor'> <class 'numpy.ndarray'>


In [39]:
a = np.random.randn(5)
print(a)
a_pt = torch.from_numpy(a)
print(a_pt)

[-0.42131633  0.48756433 -1.26708331  0.86188863 -1.59284434]
tensor([-0.4213,  0.4876, -1.2671,  0.8619, -1.5928], dtype=torch.float64)


In [40]:
np.add(a, 1, out =a)
print(a)
print(a_pt)

[ 0.57868367  1.48756433 -0.26708331  1.86188863 -0.59284434]
tensor([ 0.5787,  1.4876, -0.2671,  1.8619, -0.5928], dtype=torch.float64)


In [47]:
%%time
for i in range(100):
    a = np.random.randn(100,100)
    b = np.random.randn(100,100)
    c = a * b

CPU times: user 93 ms, sys: 732 µs, total: 93.8 ms
Wall time: 92.7 ms


In [50]:
%%time
for i in range(100):
    a = torch.randn(100,100)
    b = torch.randn(100, 100)
    c = a  *b

CPU times: user 25.7 ms, sys: 0 ns, total: 25.7 ms
Wall time: 24.4 ms


In [51]:
print(torch.cuda.device_count())

0


import numpy as np

print(torch.cuda.device_count())

In [52]:
# Autograd

In [53]:
x = torch.ones([3,2], requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [54]:
y = x +5
print(y)

tensor([[6., 6.],
        [6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)


In [55]:
z = y*y + 1
print(z)


tensor([[37., 37.],
        [37., 37.],
        [37., 37.]], grad_fn=<AddBackward0>)


In [56]:
t = torch.sum(z)
t

tensor(222., grad_fn=<SumBackward0>)

In [57]:
t.backward()

In [58]:
print(x.grad)

tensor([[12., 12.],
        [12., 12.],
        [12., 12.]])


In [59]:
x= torch.ones([3,2], requires_grad = True)
y = x +5 
r = 1/ (1+ torch.exp(-x))
print(r)

tensor([[0.7311, 0.7311],
        [0.7311, 0.7311],
        [0.7311, 0.7311]], grad_fn=<MulBackward0>)


In [60]:
s = torch.sum(r)


In [61]:
s

tensor(4.3864, grad_fn=<SumBackward0>)

In [62]:
s.backward()

In [63]:
print(x.grad)

tensor([[0.1966, 0.1966],
        [0.1966, 0.1966],
        [0.1966, 0.1966]])


In [71]:
x = torch.ones([3,2], requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], requires_grad=True)


In [76]:
x = torch.ones([3,2], requires_grad = True)

y = x+5
r = 1 / (1+ torch.exp(-y))
a = torch.ones([3,2])
r.backward(a)
print(x.grad)

tensor([[0.0025, 0.0025],
        [0.0025, 0.0025],
        [0.0025, 0.0025]])


In [77]:
x = torch.randn([20,1], requires_grad = True)
y = 3* x -2

In [83]:
w = torch.tensor([1.],requires_grad = True)
w
b= torch.tensor([1.], requires_grad = True)

In [84]:
y_hat = w * x +b

In [85]:
loss = torch.sum((y_hat - y)**2)


In [86]:
loss

tensor(138.2093, grad_fn=<SumBackward0>)

In [87]:
loss.backward()

In [88]:
w.grad

tensor([-23.3339])

In [89]:
b.grad

tensor([76.5836])

In [90]:
#loop

In [92]:
learning_rate = 0.01

w = torch.tensor([1.], requires_grad = True)
b = torch.tensor([1.], requires_grad = True)
print(w.item(), b.item())

1.0 1.0


In [93]:
for i in range(10):
    x = torch.randn([20,1])
    y = 3*x -2
    y_hat = w*x +b
    loss = torch.sum((y_hat -y)**2)
    
    loss.backward()
    
    # with - so that we tel pytoc we finsihed the compuaiton graph, i dont want annmore its time to opotimzie 
    # jsut update no book keeping
    
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        
        w.grad.zero_()
        b.grad.zero_()

      
    
    
        

In [96]:
print(w, b)

tensor([2.9767], requires_grad=True) tensor([-1.9785], requires_grad=True)
