In [1]:
import numpy as np
import torch
import torch.nn as nn

In [2]:
W = torch.randn(6)
print(W)
x= torch.tensor([10.0,10.0,10.0,10.0,10.0,10.0, ])
print(x)
b =torch.tensor(3)
print(b)

tensor([-1.5821, -1.3067, -0.6429,  1.2758, -0.6506,  0.5129])
tensor([10., 10., 10., 10., 10., 10.])
tensor(3)


In [3]:
y = W*x +b

In [4]:
y

tensor([-12.8209, -10.0674,  -3.4293,  15.7578,  -3.5059,   8.1294])

In [5]:
W*x

tensor([-15.8209, -13.0674,  -6.4293,  12.7578,  -6.5059,   5.1294])

In [6]:
import hiddenlayer as hl

In [7]:
x_train = np.array([[4.7], [2.4], [7.5], [7.1], [4.3], [7.816], [8.9],
                  [5.2], [8.59], [2.1], [8.0], [10.0], [4.5], [6.0], [4.0]], dtype= np.float32)

y_train = np.array([[2.6], [1.6], [3.09], [2.4], [2.4], [3.357], [2.6],
                  [1.96], [3.53], [1.76], [3.2], [3.5], [1.6], [2.5], [2.2]], dtype= np.float32)

In [8]:
X_train = torch.tensor(x_train)
Y_train = torch.tensor(y_train)
X_train.shape


torch.Size([15, 1])

In [12]:
inp = 1
out = 1
hid =100

In [13]:
model = torch.nn.Sequential(nn.Linear(inp, hid), torch.nn.Linear(hid,out))


In [16]:
hl.build_graph(model, torch.zeros([1]))

AttributeError: module 'torch.jit' has no attribute 'get_trace_graph'