In [1]:
import numpy as np
import torch

In [3]:
tensor = torch.rand(4,3)
print(tensor)
print(type(tensor))

tensor([[0.2155, 0.5005, 0.2783],
        [0.6644, 0.1642, 0.5323],
        [0.5127, 0.3298, 0.4303],
        [0.7822, 0.6515, 0.7483]])
<class 'torch.Tensor'>


In [5]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.21553105, 0.50048804, 0.27834082],
       [0.6643629 , 0.1642431 , 0.5323277 ],
       [0.5127471 , 0.32984018, 0.43032128],
       [0.782231  , 0.65145814, 0.7482649 ]], dtype=float32)

In [6]:
print(type(numpy_from_tensor))

<class 'numpy.ndarray'>


In [8]:
print(torch.is_tensor(tensor))

print(torch.is_tensor(numpy_from_tensor))

True
False


##### the important note 

Both numpy array created from pytorch tensor and orginal tensor share the same memory

In [9]:
tensor.fill_(2)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [10]:
numpy_from_tensor

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [12]:
numpy_arr = np.array([[1.0, 2.0], [3.0, 5.0]])

In [13]:
tensor_from_numpy = torch.from_numpy(numpy_arr)

In [14]:
tensor_from_numpy

tensor([[1., 2.],
        [3., 5.]], dtype=torch.float64)

In [17]:
# anothe method is using torch.tensor

np_arr = np.array([2,2])
np_arr


array([2, 2])

In [20]:
tesnor_np_arr = torch.tensor(np_arr)
tesnor_np_arr

tensor([2, 2])

In [21]:
np_arr[0] =6


In [22]:
np_arr

array([6, 2])

In [24]:
tesnor_np_arr # it creats the copy - same memory is not used.

tensor([2, 2])