In [1]:
import torch
print(torch.__version__)

1.4.0


In [3]:
# pytorch natively runs in float32 datatype
torch.get_default_dtype()

torch.float32

In [4]:
# lets tryo to change the default data type

torch.set_default_dtype(torch.int)

TypeError: only floating-point types are supported as the default type

 we cannot change to interger as neural networks work on floating data ,so pytorch does not allow to work on inteeger data

In [8]:
# lets try to change to float64
# yes, we can
# in totla there are 8 CUPU tensro tpyes and 8 gpu tensor types

In [7]:
torch.set_default_dtype(torch.float64)

In [11]:
tensor_arr = torch.Tensor([[1,2,3], [2,3,4]])
print(tensor_arr)

tensor([[1., 2., 3.],
        [2., 3., 4.]])


In [14]:
# checing if its tensor or not
torch.is_tensor(tensor_arr)

True

In [15]:
# to print the number of elements in the tensor
# here we have 6 elements in total 
torch.numel(tensor_arr)

6

In [16]:
torch.rand(2,2)

tensor([[0.8528, 0.9646],
        [0.3429, 0.9034]])

In [19]:
# creating tensors of of specified datatype

tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [21]:
# another way 

tensor_short = torch.ShortTensor([1.0, 2.0 ,3.0])
tensor_short

<ipython-input-21-9a8ec1d4dd63>:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  tensor_short = torch.ShortTensor([1.0, 2.0 ,3.0])


tensor([1, 2, 3], dtype=torch.int16)

In [23]:
# other 

tensor_float = torch.tensor([1.0, 2.0, 3.0]).type(torch.half)
tensor_float

tensor([1., 2., 3.], dtype=torch.float16)

In [25]:
# filling the values

tensor_fill = torch.full((2,6), fill_value =10)
print(tensor_fill)

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])


In [26]:
# filling with ones

tensor_one = torch.ones((2,3), dtype = torch.int32)
tensor_one

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)

In [28]:
# with zeros alike 
tensor_of_zeros = torch.zeros_like(tensor_one)
tensor_of_zeros

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [30]:
# identity

tensor_eye = torch.eye(5)
tensor_eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [31]:
# finding where the non zzero elements lie 

non_zero = torch.nonzero(tensor_eye)
non_zero

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4]])

In [40]:
i = torch.tensor([[0, 1,1],
                 [2,2,0]])

print(i)

tensor([[0, 1, 1],
        [2, 2, 0]])


In [42]:
v = torch.tensor([3,4,5])
v

tensor([3, 4, 5])

In [44]:
# creating sparse tensors.

sparse_tensors = torch.sparse_coo_tensor(i, v, [2,5])
sparse_tensors


tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3, 4, 5]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

# Operations in Tensors

In [45]:
initial_tensors = torch.rand(2,3)

In [46]:
initial_tensors

tensor([[0.0129, 0.3985, 0.5815],
        [0.9526, 0.2930, 0.5310]])

In [47]:
# filling with inplace 
initial_tensors.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [48]:
initial_tensors

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [49]:
initial_tensors +5

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [50]:
new_tensor = initial_tensors.add(1) # this is not in- place

In [51]:
new_tensor

tensor([[11., 11., 11.],
        [11., 11., 11.]])

In [52]:
initial_tensors

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [53]:
# add_ -> is inplace

new_tensor_ip = initial_tensors.add_(1)

In [54]:
new_tensor_ip

tensor([[11., 11., 11.],
        [11., 11., 11.]])

In [55]:
initial_tensors

tensor([[11., 11., 11.],
        [11., 11., 11.]])

In [56]:
new_tensor = initial_tensors.add_(4)


In [57]:
new_tensor

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [58]:
# lets perormf square root operation -> inplace 


new_tensor.sqrt_()

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [59]:
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [61]:
# evenly spaced Numbers
x = torch.linspace(start=0.1, end=10.0, steps =15)
print(x)

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])


In [65]:
# tensor chunk and concat operation

tensor_chunk = torch.chunk(x,3,0)
print(tensor_chunk) # along rows given by 0 as dimension

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]), tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]), tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))


In [69]:
tensor1 = tensor_chunk[0]
print(tensor1)

tensor2 = tensor_chunk[1]
print(tensor2)

tensor3 = torch.tensor([3.0, 4.0, 5.0])
print(tensor3)

torch.cat((tensor1, tensor2, tensor3),0) # along rows


tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286])
tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643])
tensor([3., 4., 5.])


tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [70]:
# Indexing and Slicing in pytorch tensors

In [74]:
random_tensor = torch.tensor([[10,8,30], [40, 5,6], [12, 2,21]])
random_tensor


tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [75]:
#indexing

random_tensor[0,1]

tensor(8)

In [76]:
# slicing

random_tensor[1:,1:]

tensor([[ 5,  6],
        [ 2, 21]])

In [78]:
# size of tensor 

random_tensor.size()

torch.Size([3, 3])

In [79]:
# view -> this does not creeate a sapce in memory 
random_tensor.view(9)

tensor([10,  8, 30, 40,  5,  6, 12,  2, 21])

In [80]:
random_tensor.view(-1, 6)

RuntimeError: shape '[-1, 6]' is invalid for input of size 9

In [81]:
random_tensor.shape

torch.Size([3, 3])

In [88]:
# adding the dimension using unsqueeze

tensor_unsqueeze = torch.unsqueeze(random_tensor, 2) # adding one dimesnion 
print(random_tensor)
print(tensor_unsqueeze)

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])
tensor([[[10],
         [ 8],
         [30]],

        [[40],
         [ 5],
         [ 6]],

        [[12],
         [ 2],
         [21]]])


In [89]:
print(random_tensor.shape)
print(tensor_unsqueeze.shape)

torch.Size([3, 3])
torch.Size([3, 3, 1])


In [90]:
# transpose of the tensor 

In [92]:
random_tensor

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [95]:
tensor_transpose = torch.transpose(random_tensor, 0,1)

In [96]:
tensor_transpose

tensor([[10, 40, 12],
        [ 8,  5,  2],
        [30,  6, 21]])

In [97]:
random_tensor

tensor([[10,  8, 30],
        [40,  5,  6],
        [12,  2, 21]])

In [98]:
# sorting

sorted_tensor, sorted_inex = torch.sort(random_tensor)

In [99]:
sorted_tensor

tensor([[ 8, 10, 30],
        [ 5,  6, 40],
        [ 2, 12, 21]])

In [100]:
sorted_inex

tensor([[1, 0, 2],
        [1, 2, 0],
        [1, 0, 2]])

In [109]:
# absolute values

tensor_float = torch.rand(2,3).type(torch.float32)
print(tensor_float)

tensor_absolute = torch.abs(tensor_float)
print(tensor_absolute)

tensor([[0.3631, 0.7515, 0.3207],
        [0.7027, 0.8406, 0.0358]], dtype=torch.float32)
tensor([[0.3631, 0.7515, 0.3207],
        [0.7027, 0.8406, 0.0358]], dtype=torch.float32)


In [110]:
# more matrix operations

In [111]:
rand1 = torch.abs(torch.rand(2,3))
rand2 = torch.abs(torch.rand(2,3))


In [115]:
add1 = rand1 + rand2
add1

tensor([[1.1372, 0.6167, 0.8280],
        [0.8364, 0.4580, 0.7069]])

In [114]:
add2 = torch.add(rand1, rand2)
add2

tensor([[1.1372, 0.6167, 0.8280],
        [0.8364, 0.4580, 0.7069]])

In [117]:
tensor_mul = torch.mul(rand1, rand2)
tensor_mul

tensor([[0.2602, 0.0009, 0.1638],
        [0.1484, 0.0464, 0.0677]])

In [118]:
# tenosr clamp

tensor_clamp = torch.clamp(tensor_mul, min =0.2, max=2)
tensor_clamp

tensor([[0.2602, 0.2000, 0.2000],
        [0.2000, 0.2000, 0.2000]])

In [119]:
# lets perform some matrix operations

t1 = torch.tensor([1,2])
t2 = torch.tensor([10,20])



In [120]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50)

In [122]:
# matrix and vector multiplicaion

matrix = torch.tensor([[1,2,3],
                      [4,5,6]])

vector = torch.tensor([0,1,2])




In [125]:
matrix_vector = torch.mv(matrix, vector)
print(matrix_vector)

tensor([ 8, 17])


In [127]:
matrix_vector1 = torch.mv(vector, matrix)
print(matrix_vector1) # shape do not match

RuntimeError: matrix and vector expected, got 1D, 2D at /pytorch/aten/src/TH/generic/THTensorMath.cpp:287

In [128]:
# matrix - matrix Multiplication

another_matrxi = torch.tensor([[10,30],
                              [20,0],
                              [0, 50]])
another_matrxi

tensor([[10, 30],
        [20,  0],
        [ 0, 50]])

In [129]:
mat_mat = torch.mm(matrix, another_matrxi)
mat_mat

tensor([[ 50, 180],
        [140, 420]])

In [130]:
torch.argmax(mat_mat, dim =1)

tensor([1, 1])

In [131]:
torch.argmax(mat_mat, dim =0)

tensor([1, 1])